# Generated by Django 4.0.3 on 2022-04-07 19:30

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('code', models.CharField(default=authentication.models.get_random_digits, editable=False, max_length=6)),
                ('expiration_date', models.DateTimeField(default=authentication.models.get_expiration_date, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forget_records', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('expired_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
