# Generated by Django 4.0.3 on 2022-04-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_forgetrecord'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='forgetrecord',
            managers=[
            ],
        ),
    ]
