# Generated by Django 4.0.3 on 2022-04-14 08:08

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_forgetrecord_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=authentication.models.get_verification_code, editable=False, max_length=32)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
