# Generated by Django 4.0.3 on 2022-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='design',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
