# Generated by Django 4.0.3 on 2022-03-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_color_text_alter_design_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_model', to='product.model'),
        ),
    ]
