# Generated by Django 4.0.3 on 2022-03-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightskyproduct',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
