# Generated by Django 4.0.3 on 2022-03-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_nightskyproduct_frame_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightskyproduct',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_sky_products', to='product.color'),
        ),
        migrations.AlterField(
            model_name='nightskyproduct',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_sky_products', to='product.design'),
        ),
        migrations.AlterField(
            model_name='nightskyproduct',
            name='font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_sky_products', to='product.font'),
        ),
        migrations.AlterField(
            model_name='nightskyproduct',
            name='map_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_sky_products', to='product.mapdesign'),
        ),
        migrations.AlterField(
            model_name='nightskyproduct',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_sky_product', to='product.model'),
        ),
        migrations.AlterField(
            model_name='nightskyproduct',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_sky_product', to='product.size'),
        ),
    ]
