# Generated by Django 4.0.3 on 2022-03-25 11:10

import chatroom.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_is_sender', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=1024)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=chatroom.models.get_message_path)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_messages', to='shop.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
