# Generated by Django 4.0.3 on 2022-03-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_nightskyproduct_frame_color'),
        ('shop', '0002_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='product.nightskyproduct'),
        ),
    ]
